version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: apache/Dockerfile
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    volumes:
      - ./src:/var/www/html
      - ./apache/ssl:/etc/apache2/ssl
      - ./apache/conf/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./apache/conf/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - resourcespace
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
    healthcheck:
      test: "exit 0"
    networks:
      - resourcespace
volumes:
  db:
networks:
  resourcespace:
    driver: bridge